spring.application.name=game-finder
spring.h2.console.enabled=true
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.url=jdbc:h2:file:./data/egame-finderdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.defer-datasource-initialization=true
spring.h2.console.path=/h2-console
spring.hateoas.use-hal-as-default-json-media-type=true